### ISSUE TITLE
unknown flag: --auto-approve

### ISSUE THREAD

**Issue by ibmer921150** [logandavies181/tfd#3]
Use tfd latest version: v1.1.0
Referring README to run below command. It shows `unknown flag: --auto-approve`. Is it actual `auto-apply` ?

![image](https://user-images.githubusercontent.com/13460590/131759921-3b240fdf-1e51-4425-a7e8-f45841a7acd5.png)

**Comment by logandavies181** [comment]
I have updated the README to use the correct flag. Thank you!
