### ISSUE TITLE
If tfd is waiting for completion of an `apply` that fails, tfd does not report an error

### ISSUE THREAD

**Issue by adrian-kiwibank** [logandavies181/tfd#8]
It would be useful if tfd returned a non-zero error code if any terraform operation it is waiting for completes with errors.

For example the following tfd run returned with code 0 and reported the wrong number of changes:
```
$ tfd run start --auto-apply
run-aaaaaaaaaa
Plan plan-bbbbbbbbb running. Waiting for it to finish..
Plan: 22 to add, 1 to change, 39 to destroy.
Run confirmed
Waiting for apply..
Run finished
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

The actual result in terraform was:
 - Apply errored, 19 created, 38 destroyed.

(running tfd 1.1.1)

**Comment by logandavies181** [comment]
Fixed in v1.2.0. Thanks!
